// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paro.Utils;

#nullable disable

namespace Paro.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20261001205604_AlteraTabelaSala")]
    partial class AlteraTabelaSala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Paro.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Nome"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Animal"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Fruta"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Cor"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Objeto"
                        });
                });

            modelBuilder.Entity("Paro.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdentificaOrganizador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Paro.Models.Rodada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Letra")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Rodadas");
                });

            modelBuilder.Entity("Paro.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRodadas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Paro.Models.Categoria", b =>
                {
                    b.HasOne("Paro.Models.Rodada", null)
                        .WithMany("Categorias")
                        .HasForeignKey("RodadaId");
                });

            modelBuilder.Entity("Paro.Models.Jogador", b =>
                {
                    b.HasOne("Paro.Models.Sala", null)
                        .WithMany("Jogadores")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paro.Models.Rodada", b =>
                {
                    b.HasOne("Paro.Models.Sala", null)
                        .WithMany("Rodadas")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paro.Models.Rodada", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Paro.Models.Sala", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("Rodadas");
                });
#pragma warning restore 612, 618
        }
    }
}
